name: Check

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v -o wtt.out

    - uses: actions/upload-artifact@v4
      with:
        name: build
        path: wtt.out
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Test
      run: go test -v -coverprofile=coverage.out ./...

    - uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage.out